name: Lint & Format

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint-fix

      - name: Run Prettier
        run: npm run prettier-fix

      - name: Commit changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote remove origin
          git remote add origin https://BTS-Busan-Trip-Supporter:${{ secrets.CI_TOKEN }}@github.com/BTS-Busan-Trip-Supporter/front-end.git
          git diff --quiet || (git add . && git commit -m 'chore: auto-fix linting and formatting issues' && git push --set-upstream origin ${{ github.head_ref }})
